name: Java

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checkout your repository
        - name: Checkout code
          uses: actions/checkout@v4

        # Set up Java 17
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: temurin

        # Cache Gradle dependencies
        - name: Cache Gradle packages
          uses: actions/cache@v3
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper/
            key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              gradle-${{ runner.os }}-

        # Run Gradle build and tests
        - name: Build and test
          run: ./gradlew clean build --stacktrace
